export const blocks = {
  qwik: [
    'Alert',
    'Banners',
    'Breadcrumbs',
    'Card',
    // 'Checkout',
    // 'Combobox',
    // 'Filters',
    'Footer',
    // 'FormFields',
    // 'Gallery',
    // 'MegaMenu',
    'NavbarBottom',
    'NavbarTop',
    'NewsletterBox',
    'OrderSummary',
    // 'Pagination',
    // 'ProductCard',
    // 'ProductSlider',
    // 'QuantitySelector',
    // 'RatingForms',
    // 'Review',
    // 'Search',
    // 'SelectDropdown',
    // 'Tabs',
  ],
};
