export const components = {
  qwik: [
    'SfAccordionItem',
    'SfBadge',
    'SfButton',
    'SfCheckbox',
    'SfChip',
    'SfCounter',
    'SfDrawer',
    'SfDropdown',
    'SfIconBase',
    'SfInput',
    'SfLink',
    'SfListItem',
    'SfLoaderCircular',
    'SfLoaderLinear',
    'SfModal',
    'SfProgressCircular',
    'SfProgressLinear',
    'SfRadio',
    'SfRating',
    // 'SfRatingButton',
    // 'SfScrollable',
    // 'SfSelect',
    'SfSwitch',
    'SfTextarea',
    // 'SfThumbnail',
    // 'SfTooltip',
  ],
};
